#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status.
set -x  # All executed commands are printed to the terminal

export DEBIAN_FRONTEND=noninteractive

aptitude update ; apt-get install -y hitch

mkdir -p /var/lib/hitch/
cp /tmp/contents/static/hitch.conf /etc/hitch/

sed -i '$i hitch --daemon --config /etc/hitch/hitch.conf --sni-nomatch-abort --workers auto -u _hitch -g _hitch -l /etc/hitch/log.txt > /dev/null 2>&1' /usr/local/boot
sed -i '$i bash -c '\''while true; do sleep 10; pgrep hitch || killall -9 bash; done'\'' > /dev/null 2>&1 &' /usr/local/boot

apt-get -y autoremove ; aptitude -y autoclean ; apt-get -y autoclean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.aptitude
